/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Windows 11
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
        public TelaPrincipal() {
            initComponents();
            
            setExtendedState(MAXIMIZED_BOTH);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrinc = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuHosp = new javax.swing.JMenu();
        MenuCadHosp = new javax.swing.JMenuItem();
        MenuConsHosp = new javax.swing.JMenuItem();
        MenuQuar = new javax.swing.JMenu();
        MenuCadQuar = new javax.swing.JMenuItem();
        MenuConsQuar = new javax.swing.JMenuItem();
        MenuFunc = new javax.swing.JMenu();
        MenuCadFunc = new javax.swing.JMenuItem();
        MenuConsFunc = new javax.swing.JMenuItem();
        MenuReservas = new javax.swing.JMenu();
        MenuFazerR = new javax.swing.JMenuItem();
        MenuConsR = new javax.swing.JMenuItem();
        MenuFinR = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        MenuRelFinanc = new javax.swing.JMenuItem();
        MenuRelRes = new javax.swing.JMenuItem();
        MenuRelHosp = new javax.swing.JMenuItem();
        MenuRelFunc = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Habbo Hotel");

        MenuCadastros.setText("Cadastros  ");

        MenuHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Hospedes.png"))); // NOI18N
        MenuHosp.setText("Hóspedes");

        MenuCadHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Cadastrar.png"))); // NOI18N
        MenuCadHosp.setText("Cadastrar");
        MenuCadHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadHospActionPerformed(evt);
            }
        });
        MenuHosp.add(MenuCadHosp);

        MenuConsHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Cons.png"))); // NOI18N
        MenuConsHosp.setText("Consultar");
        MenuHosp.add(MenuConsHosp);

        MenuCadastros.add(MenuHosp);

        MenuQuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Quartos.png"))); // NOI18N
        MenuQuar.setText("Quartos");

        MenuCadQuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Cadastrar.png"))); // NOI18N
        MenuCadQuar.setText("Cadastrar");
        MenuQuar.add(MenuCadQuar);

        MenuConsQuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Cons.png"))); // NOI18N
        MenuConsQuar.setText("Consultar");
        MenuQuar.add(MenuConsQuar);

        MenuCadastros.add(MenuQuar);

        MenuFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Funcionarios.png"))); // NOI18N
        MenuFunc.setText("Funcionários");

        MenuCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Cadastrar.png"))); // NOI18N
        MenuCadFunc.setText("Cadastrar");
        MenuCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadFuncActionPerformed(evt);
            }
        });
        MenuFunc.add(MenuCadFunc);

        MenuConsFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/Cons.png"))); // NOI18N
        MenuConsFunc.setText("Consultar");
        MenuFunc.add(MenuConsFunc);

        MenuCadastros.add(MenuFunc);

        MenuPrinc.add(MenuCadastros);

        MenuReservas.setText("Reservas  ");

        MenuFazerR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/FazerR.png"))); // NOI18N
        MenuFazerR.setText("Fazer Reserva");
        MenuReservas.add(MenuFazerR);

        MenuConsR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/ConsR.png"))); // NOI18N
        MenuConsR.setText("Consultar Reserva");
        MenuReservas.add(MenuConsR);

        MenuFinR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/FinR.png"))); // NOI18N
        MenuFinR.setText("Finalizar Reserva");
        MenuReservas.add(MenuFinR);

        MenuPrinc.add(MenuReservas);

        MenuRelatorios.setText("Relatórios  ");

        MenuRelFinanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/RelFin.png"))); // NOI18N
        MenuRelFinanc.setText("Finaceiro");
        MenuRelatorios.add(MenuRelFinanc);

        MenuRelRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/RelRes.png"))); // NOI18N
        MenuRelRes.setText("Reservas");
        MenuRelatorios.add(MenuRelRes);

        MenuRelHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/RelHosp.png"))); // NOI18N
        MenuRelHosp.setText("Hóspedes");
        MenuRelatorios.add(MenuRelHosp);

        MenuRelFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/RelFunc.png"))); // NOI18N
        MenuRelFunc.setText("Funcionários");
        MenuRelatorios.add(MenuRelFunc);

        MenuPrinc.add(MenuRelatorios);

        MenuSair.setText("Sair");
        MenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuPrinc.add(MenuSair);

        setJMenuBar(MenuPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCadHospActionPerformed

    private void MenuCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCadFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCadFunc;
    private javax.swing.JMenuItem MenuCadHosp;
    private javax.swing.JMenuItem MenuCadQuar;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenuItem MenuConsFunc;
    private javax.swing.JMenuItem MenuConsHosp;
    private javax.swing.JMenuItem MenuConsQuar;
    private javax.swing.JMenuItem MenuConsR;
    private javax.swing.JMenuItem MenuFazerR;
    private javax.swing.JMenuItem MenuFinR;
    private javax.swing.JMenu MenuFunc;
    private javax.swing.JMenu MenuHosp;
    private javax.swing.JMenuBar MenuPrinc;
    private javax.swing.JMenu MenuQuar;
    private javax.swing.JMenuItem MenuRelFinanc;
    private javax.swing.JMenuItem MenuRelFunc;
    private javax.swing.JMenuItem MenuRelHosp;
    private javax.swing.JMenuItem MenuRelRes;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuReservas;
    private javax.swing.JMenu MenuSair;
    // End of variables declaration//GEN-END:variables
}
